
services:
  #python:
  #  build: ./src
  
  create_data:
    build:
      context: ./src/create_data
      dockerfile: ./Dockerfile
    environment:
      POSTGRES_HOST: ${DATA_ARRIVAL_POSTGRES_HOST}
      POSTGRES_PORT: ${DATA_ARRIVAL_POSTGRES_PORT}
      POSTGRES_USER: ${DATA_ARRIVAL_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DATA_ARRIVAL_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DATA_ARRIVAL_POSTGRES_DB}
      DATA_TABLE: ${DATA_ARRIVAL_DATA_TABLE}
  
  consume_data:
    build:
      context: ./src/consume_data
      dockerfile: ./Dockerfile
    environment:
      POSTGRES_HOST: ${DWH_POSTGRES_HOST}
      POSTGRES_PORT: ${DWH_POSTGRES_PORT}
      POSTGRES_USER: ${DWH_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DWH_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DWH_POSTGRES_DB}
      DATA_TABLE: ${DWH_DATA_TABLE}

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    restart: always

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DATA_ARRIVAL_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DATA_ARRIVAL_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DATA_ARRIVAL_POSTGRES_DB}
    ports:
      - ${DATA_ARRIVAL_POSTGRES_EXTERNAL_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: >
      postgres -c wal_level=logical
               -c max_replication_slots=5
               -c max_wal_senders=5
    
  dwh:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DWH_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DWH_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DWH_POSTGRES_DB}
    ports:
      - ${DWH_POSTGRES_EXTERNAL_PORT}:5432
    volumes:
      - dwh_data:/var/lib/postgresql/data

  debezium:
    image: quay.io/debezium/connect:latest
    depends_on:
      - kafka
      - postgres
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: debezium_config
      OFFSET_STORAGE_TOPIC: debezium_offset
      STATUS_STORAGE_TOPIC: debezium_status
      CONNECTORS_CONFIG_DIR: /kafka/connectors
    ports:
      - "8083:8083"
    volumes:
      - ./connectors:/kafka/connectors

volumes:
  postgres_data:
  dwh_data: